language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - ./node_modules
    - ./bower_components
    - ./test/node_modules

install:
  - cd test && npm install && cd ..

script:
  - cd test
  - ./node_modules/karma/bin/karma start karma.conf.js
